name: TreeAdoption

options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "nl.tadas.treeadoption"
  deploymentTarget: 14.0
  SWIFT_VERSION: "5"

targets:

  TreeAdoption:
    type: application
    platform: iOS
    sources:
      - path: TreeAdoption
    deploymentTarget: 14.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nl.tadas.treeadoption
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      configs:
        Debug:
          DEBUG_MODE: YES
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
        Release:
          DEBUG_MODE: NO
          PROVISIONING_PROFILE_SPECIFIER: match AppStore nl.tadas.treeadoption
          CODE_SIGN_IDENTITY: Apple Distribution
          CODE_SIGN_STYLE: Manual
    preBuildScripts:
      - script: "${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat $SRCROOT"
        name: "SwiftFormat autocorrect"
      - script: "${PODS_ROOT}/SwiftLint/swiftlint --strict"
        name: "Check if we pass SwiftLint"
